### PR TITLE
Only auto-init polyfill inside browser context

### PR DESCRIPTION
**Pull request by jelmerdemaat**
This PR is related to #17.

I feel like the auto initialisation function doesn't belong where it is now. `objectFitPolyfill()` is `undefined` at the point that the initialisation is done when the JS is build via a compiler like Babel, and `window` and `document` only exist in the browser context.

This fix is a suggestion and I don't know if it's the best solution. :)

### CODE REVIEW

**Comment by cee-chen** [comment]
Hey Jelmer! Thanks so much for your suggestion and figuring out where the issue is (when using the polyfill in a compiler/bundler). I've only ever used my polyfill by chucking it directly in the browser, so I feel super bad for not having tested other options.

I'm trying to look up/figure out best practices for polyfills, and it looks like perhaps [I should not put it in a UMD wrapper](https://webreflection.blogspot.com/2014/03/do-not-require-polyfills.html) at all. 🤔 Any thoughts? Would it be simpler to drop the wrapper, return `window.objectFitPolyfill()` and call the 2 event listeners all in the global scope?

**Comment by cee-chen** [comment]
I checked out your fork+branch - it works great client side, but when I tried running it through module bundler like webpack, but it was unfortunately still throwing errors for me. I think I'm just going to ditch the UMD wrapper entirely, since it doesn't seem to be working - and since the functionality/intention of this polyfill is supposed to be mostly automatic (as opposed to people having to call/run the module manually).

Thanks so much for pointing me in the right direction of the problem, Jelmer! Could you let me know if the latest dist works for you? (I'll be at a convention this weekend, but I'll try to hop on issue #17 asap!)

**Comment by jelmerdemaat** [comment]
Yes, your fix totally works for me! Great! :+1:

**Comment by darrenjacoby** [comment]
I'm struggling to get this working with Browserify and ES6.  

At the moment I have; 

`import 'objectFitPolyfill';`
`window.objectFitPolyfill();`

Is this the correct usage for v2.0.4?

**Comment by cee-chen** [comment]
Heya Darren,

Feel free to open a new issue for this - I don't want to spam Jelmer a bunch!

To answer your question, though, you should just need `import 'objectFitPolyfill';` - on page load, `objectFitPolyfill();` gets called automatically. If you need to manually re-run the polyfill for any reason, then yeah, you can go ahead and call `objectFitPolyfill();` or `window.objectFitPolyfill();`.

I have a demo of this up on requireBin - you can check out the code [here](http://requirebin.com/?gist=5bfad2681376e54044ed0156d5fbe2d8) and the output [here](http://requirebin.com/embed?gist=5bfad2681376e54044ed0156d5fbe2d8).

**Comment by darrenjacoby** [comment]
Hey @constancecchen , thanks so much!  

Using `require('objectFitPolyfill')` did it.  And thank you for the polyfill, really great!

**Pull request closed without merging**
